config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get 'home/about', to: 'homes#about', as: 'about'
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get "search" => 'searches'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
   
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
  relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
  followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resources)
    user_path(resources)
  end

  def after_sign_out_path_for(resources)
    root_path
  end

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end

  def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
  end

  def edit
   @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :index
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
 before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]
    @search = params[:serch]
    @book = Book.all

    if @range == "user"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
       redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<p id="notice"></p>
  <div class="col-md-3">
   <h4>User info</h4>

<%= image_tag user.get_profile_image(100, 100) %>

<table class="table table">
  <tbody>
     <tr></tr>
     <tr>
      <th>name</th>
      <th><%= user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
     </tr>
     <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
     </tr>
     <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
     </tr>
  </tbody>
</table>
<div class="row">
　　<% if user == current_user %>
     <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
       <i class="fas fa-user-cog"></i>
     <% end %>
    <% end %>

　　<% unless current_user == user %>
　　　<% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info btn-sm btn-block" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success btn-sm btn-block" %>
      <% end %>
   <% end %>
</div>

<h4 class= "mt-3">New book</h4>

<%= form_with model:book do |f| %>

 <div class="form-group">
 <h6>Title</h6>
 <%= f.text_field :title %>
 </div>

 <div class="form-group">
 <h6>Opinion</h6>
 <%= f.text_area :body %>
 </div>
<div class="form-group">
 <%= f.submit 'Create Book' %>
 </div>
<% end %>

</div>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
   <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
  <% end %>

<%= form_with model: @book do |f| %>

 <h4>Title</h4>
  <%= f.text_field :title %>

 <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>
<% end %>

<p>
 <%= link_to "Show", book_path(@book.id) %>
 <%= link_to "Back", books_path %>
</p>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
   <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
   <% end %>  
  <div class="row">

<%= render 'books/list', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h4>Books</h4>

<table class="table table-hover rable-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
<% @books.each do |book| %>
<tr>
<td>
<%= link_to user_path(book.id) do %>
<%= image_tag book.user.get_profile_image(100,100) %>
<% end %>
</td>

<td><%= link_to book.title ,book_path(book.id) %></td>
<td><%= book.body %></td>
</tr>

<% end %>
</tbody>
</div>
</table>
</div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'books/list', user: @user, book: @new_book %>

<div class="col-md-8 offset-md-1">
<h4>Book detail</h4>

<table class="table">
 <thead>
     <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
     </tr>
 </thead>
 <tbody>
     <tr>
         <td>
             <%= link_to user_path(@user.id) do %>
              <p><%= image_tag @book.user.get_profile_image(100,100) %></p>
              <p><%= @user.name %></p>
             <% end %>
         </td>
         <td><%= link_to @book.title ,book_path(@book.id) %></td>
         <td><%= @book.body %></td>
         <% if @user == current_user %>
         <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
         <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
         <% end %>
         </tr>
     </tbody>
   </table>
   </div>
  </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<h1>Welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!!</h1>
<p>In <strong><i class="fas fa-book"></i>Bookers</strong>,</p>

<p>you can share and exchange your opinions, inspressions, and emotions</p>
<p>about various books!</p>

<%= link_to "Log in",new_user_session_path, class: "btn btn-info btn-sm btn-block" %>

<%= link_to "Sign up",new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                  <span><i class="fas fa-home"></i> Home</span>
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <span><i class="fas fa-users"></i> Users</span>
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <span><i class="fas fa-book-open"></i> Books</span>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                  <span><i class="fas fa-sign-out-alt"></i> Log out</span>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <span><i class="fas fa-home"></i> Home</span>
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: "nav-link text-light" do %>
                  <span><i class="fas fa-link"></i> About</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                  <span><i class="fas fa-user-plus"></i> Sign up</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                  <span><i class="fas fa-sign-in-alt"></i> Log in</span>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= flash[:notice] %>
    <main class="mt-3">
      <div class="d-flex justify-content-center mb-2">
        <% if user_signed_in? %>
       <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select({ "User" => "user", "Book" => "book" }) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
    </div>
   <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/followers.html.erb
<h4>Follower Users</h4>

<% if @users.exists? %>
  <% @users.each do |user| %>
  <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image(100, 100) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show" ,user_path(user.id) %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h4>Follow Users</h4>

<% if @users.exists? %>
  <% @users.each do |user| %>
  <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image(100, 100) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show" ,user_path(user.id) %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searches/search.html.erb
<% if @range == 'user' %>
	<h3>Users search for "<%= @word %>"</h3>
	<table class="table table-hover table-inverse">
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
        </tr>
      <% end %>
  </tbody>
  </table>
  <% elsif @range == 'book' %>
	<h3>Books search for "<%= @word %>"</h3>
	<table class="table table-hover table-inverse">
  <thead>
    <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
    </tr>
  </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image(100,100) %></td>
          <td><%= link_to book.title ,book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
    <%= @user.errors.count %>error prohibited this obj from being saved:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
   <% end %>

<%= form_with model: @user do |f| %>

  <h4>Name</h4>
  <%= f.text_field :name %>

  <h4>Image</h4>
  <%= f.file_field :profile_image, accept: "image/*" %>

  <h4>Introduction</h4>
  <%= f.text_area :introduction %>

  <%= f.submit 'Update User' %>

<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'books/list', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h4>Users</h4>

<table class="table">
<thead>
  <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
</thead>
<% @users.each do |user| %>
<tbody>
  <tr>
    <td><%= image_tag user.get_profile_image(100, 100) %></td>
    <td><%= user.name %></td>
    <td>フォロー数<%= user.followings.count %></td>
    <td>フォロワー数<%= user.followers.count %></td>
    <td>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
      <% end %>
    </td>
    <td><%= link_to "Show" ,user_path(user.id) %></td>
  </tr>
   <% end %>
   </tbody>
  </table>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'books/list', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h4>Books</h4>

<table class="table table-hover rable-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
   <tr>
     <td>
       <%= link_to user_path(@user.id) do %>
       <%= image_tag book.user.get_profile_image(100,100) %><br>
       <% end %>
     </td>
     <td><%= link_to book.title ,book_path(book.id) %></td>
     <td><%= book.body %></td>
     <% end %>
    </tr>
   </tbody>
  </table>
 </div>
</div>
</div>